FROM python:3.8

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY ./app /app
COPY ./localhost.pem ./
COPY ./localhost-key.pem ./
CMD [ "uvicorn", "app.main:app_auth", "--reload", "--host", "0.0.0.0", "--port", "5000", "--ssl-keyfile", "./localhost-key.pem", "--ssl-certfile", "./localhost.pem"]
