version: "3.8"

services:
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile_chat
    volumes:
      - ../backend/app:/app
    ports:
      - 5010:5010
    restart: unless-stopped