version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../frontend:/frontend
      - ../frontend/node_modules:/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
